-- Create Books Table
CREATE TABLE public.books (
  id bigint generated by default as identity primary key,
  stock_number text not null unique,
  title text not null,
  author text not null,
  language text,
  category text,
  price numeric,
  book_type text,
  status boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;

-- Policy: Public can read (excluding price for public view - handled in frontend)
CREATE POLICY "Public Read Access" ON public.books FOR SELECT USING (true);

-- Policy: Admin Full Access (Requires Auth)
CREATE POLICY "Admin Insert Access" ON public.books FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Admin Update Access" ON public.books FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Admin Delete Access" ON public.books FOR DELETE TO authenticated USING (true);